### ISSUE TITLE
Adjust disk size correctly

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/azure-resource-manager-neo4j#15]
Right now the disk size parameter is setting the size on a data disk.  The data disk is not mounted.

To do --- 
(1) use the disk size parameter to adjust the size of the osdisk
(2) remove the data disk
(3) republish the azure listing

**Comment by edrandall-dev** [comment]
This has been resolved.  Data disk is now mounted correctly at /var/lib/neo4j
