### ISSUE TITLE
Set Up SSL for HTTP and Bolt

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/azure-resource-manager-neo4j#4]
Right now only HTTPS is enabled.  I'm missing something in the setup.

**Comment by benofben** [comment]
seem to be working for bolt.  Not for cluster or backup though.

**Comment by benofben** [comment]
SSL for Bolt and HTTP is currently being setup but something isn't right.  It's using a self signed cert.  You can bypass the self signed cert.  You're then presented with the Neo4j Browser login screen.  However, it's not possible to login.  One possibility is that the javascript driver embedded in the browser wants a proper cert.  Another possibility is that the self signed cert config is somehow wrong.  We're not currently sure which it is.

The current thinking is that we do want SSL configured with a self signed cert for bolt and http by default.  We would not do that for backup and cluster however.

**Comment by harshitsinghvi22** [comment]
SSL cannot be implemented as it required certs before hand...self signed certs still does not solve the problem as the browser showcases invalid cert or missing cert and fails to load the url...this could be part of custom solution but not part of the main template deployed in marketplace
