### ISSUE TITLE
Bump default deploy to 8 core

### ISSUE THREAD

**Issue by benofben** [neo4j-partners/azure-resource-manager-neo4j#6]
2 seems too light based on our recent lab work

**Comment by drumcircle** [comment]
On it

**Comment by drumcircle** [comment]
8 cores is $0.50/hour - $12/day. Upped to r6i.2xlarge (feature/6_update_configuration)

**Comment by benofben** [comment]
r6 is an AWS machine.

Done w Standard E8.
